sudo: required
language:
  - cpp
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libopencv-dev
            - libhdf5-serial-dev
            - libhdf5-dev
            - libcurl3
            - libcurl4-openssl-dev
            - libcfitsio3-dev
            - libccfits-dev
            - mercurial
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - pwd
     - cmake -DCMAKE_BUILD_TYPE=Release ..
     - make
