sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - libopencv-dev
      - libhdf5-serial-dev
      - libhdf5-dev
      - libcurl3
      - libcurl4-openssl-dev
      - libcfitsio3-dev
      - libccfits-dev
      - mercurial
      - cmake
script:
     - pwd
     - hg clone https://bitbucket.org/eigen/eigen/
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - pwd
     - cmake -DCMAKE_BUILD_TYPE=Release -DEIGEN3_INCLUDE_DIR=../eigen/ ..
     - make
